#!/usr/bin/env -S nix develop . -c zsh

print -P %F{yellow}Cleaning repository%f
nix develop -c cabal clean

(git ls-files test examples; git ls-files '*.cabal'; git ls-files 'flake.*') | \
  entr -r \
    nix develop -c \
      ghcid \
        --warnings \
        "--command=cabal repl lib:quasar-wayland" \
        "--test=:! \
          cabal test --disable-optimisation --enable-debug-info=2 --test-show-details=direct --ghc-option -fdiagnostics-color=always && \
          cabal run --disable-optimisation --enable-debug-info=2 --ghc-option -fdiagnostics-color=always quasar-wayland-example-client && \
          zsh -c 'print -P %F{green}Build and tests passed%f' \
        "
