module Quasar.Wayland.Protocol (
  -- * Wayland wire protocol
  -- | This module exports everything required to implement Wayland interfaces generated by
  -- "Quasar.Wayland.Protocol.TH".

  Object,

  -- ** Wire types
  ObjectId,
  GenericObjectId,
  NewId,
  Fixed(..),
  WlString(..),

  -- ** Classes for generated interfaces
  IsInterface(InterfaceName),
  interfaceName,
  Side(..),
  IsSide,

  -- ** Protocol execution
  ProtocolHandle,
  initializeProtocol,
  feedInput,
  takeOutbox,
  setException,

  -- ** Low-level protocol interaction (TODO should no longer be required after cleanup)
  ProtocolM,
  runProtocolTransaction,
  runProtocolM,
  newObject,
  sendMessage,

  -- * Protocol exceptions
  WireCallbackFailed(..),
  ParserFailed(..),
  ProtocolException(..),
  MaximumIdReached(..),
  ServerError(..),
) where

import Quasar.Wayland.Protocol.Core
