module Quasar.Wayland.Protocol (
  -- * Wayland wire protocol
  -- | This module exports everything required to implement Wayland interfaces generated by
  -- "Quasar.Wayland.Protocol.TH".

  Object,
  setEventHandler,
  setRequestHandler,
  setMessageHandler,
  getMessageHandler,

  -- ** Wayland types
  Fixed(..),
  WlString(..),

  -- ** Protocol execution
  ProtocolHandle,
  initializeProtocol,
  feedInput,
  takeOutbox,
  setException,

  -- * Protocol exceptions
  WireCallbackFailed(..),
  ParserFailed(..),
  ProtocolException(..),
  MaximumIdReached(..),
  ServerError(..),

  -- ** Classes for generated interfaces
  IsInterface(InterfaceName),
  interfaceName,
  Side(..),
  IsSide,
) where

import Quasar.Wayland.Protocol.Core
